package com.keysersoze.yumyard.ui.theme

import androidx.compose.ui.graphics.Color

val YumOrange = Color(0xFFED7922)
val YumOrangeDeep = Color(0xFFB85A10)
val YumGold = Color(0xFFFAA306)
val YumCream = Color(0xFFFAEED8)
val YumPurple = Color(0xFF1B0E20)
val YumTomato = Color(0xFFE61101)
val YumBasil = Color(0xFF5DA85A)

val DarkPrimary = YumOrange
val DarkOnPrimary = Color(0xFF221006)
val DarkPrimaryContainer = Color(0xFF5A2E0A)
val DarkOnPrimaryContainer = Color(0xFFFFDCC2)
val DarkSecondary = YumGold
val DarkOnSecondary = Color(0xFF2A1D00)
val DarkSecondaryContainer = Color(0xFF5C4300)
val DarkOnSecondaryContainer = Color(0xFFFFE08A)
val DarkTertiary = Color(0xFF7FCf7C)
val DarkOnTertiary = Color(0xFF06280C)
val DarkTertiaryContainer = Color(0xFF204622)
val DarkOnTertiaryContainer = Color(0xFFB7F0B0)
val DarkBackground = Color(0xFF170D1C)
val DarkOnBackground = Color(0xFFF3E9DA)
val DarkSurface = Color(0xFF1F1226)
val DarkOnSurface = Color(0xFFF3E9DA)
val DarkSurfaceVariant = Color(0xFF2C1E33)
val DarkOnSurfaceVariant = Color(0xFFD6C6D0)
val DarkSurfaceContainer = Color(0xFF241531)
val DarkSurfaceContainerHigh = Color(0xFF2E1C3D)
val DarkOutline = Color(0xFF7A6A82)
val DarkError = Color(0xFFE6483B)
val DarkOnError = Color(0xFF2B0A06)
val DarkErrorContainer = Color(0xFF7A1109)
val DarkOnErrorContainer = Color(0xFFFFDAD5)

val LightPrimary = YumOrangeDeep
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDCC2)
val LightOnPrimaryContainer = Color(0xFF351400)
val LightSecondary = Color(0xFF8A6A00)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFE08A)
val LightOnSecondaryContainer = Color(0xFF2A1D00)
val LightTertiary = Color(0xFF2E6B34)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFB7F0B0)
val LightOnTertiaryContainer = Color(0xFF06280C)
val LightBackground = Color(0xFFFFF8EE)
val LightOnBackground = Color(0xFF241019)
val LightSurface = Color(0xFFFFFCF7)
val LightOnSurface = Color(0xFF241019)
val LightSurfaceVariant = Color(0xFFF3E3D2)
val LightOnSurfaceVariant = Color(0xFF52443B)
val LightSurfaceContainer = Color(0xFFFCEEDD)
val LightSurfaceContainerHigh = Color(0xFFF7E7D3)
val LightOutline = Color(0xFF857567)
val LightError = Color(0xFFC0160B)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD5)
val LightOnErrorContainer = Color(0xFF410002)
